use_default_settings: true

default_doi_resolver: ''  # âœ… Corrige l'erreur fatale

server:
  secret_key: "ultrasecretkey"  # ğŸ” Ã  changer pour production
  limiter: false
  image_proxy: true

# redis:
#   url: redis://redis:6379/0  # âŒ DÃ©sactivÃ© car l'hÃ´te "redis" n'existe pas sur Koyeb
