---
name: Update searx.data

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "59 23 28 * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.13"

jobs:
  data:
    if: github.repository_owner == 'searxng'
    name: ${{ matrix.fetch }}
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        fetch:
          - update_ahmia_blacklist.py
          - update_currencies.py
          - update_external_bangs.py
          - update_firefox_version.py
          - update_engine_traits.py
          - update_wikidata_units.py
          - update_engine_descriptions.py

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          persist-credentials: "false"

      - name: Setup cache Python
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809  # v4.2.4
        with:
          key: "python-${{ env.PYTHON_VERSION }}-${{ runner.arch }}-${{ hashFiles('./requirements*.txt') }}"
          restore-keys: "python-${{ env.PYTHON_VERSION }}-${{ runner.arch }}-"
          path: "./local/"

      - name: Setup venv
        run: make V=1 install

      - name: Fetch data
        run: V=1 ./manage pyenv.cmd python "./searxng_extra/update/${{ matrix.fetch }}"

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e  # v7.0.8
        with:
          author: "searxng-bot <searxng-bot@users.noreply.github.com>"
          committer: "searxng-bot <searxng-bot@users.noreply.github.com>"
          title: "[data] update searx.data - ${{ matrix.fetch }}"
          commit-message: "[data] update searx.data - ${{ matrix.fetch }}"
          branch: "update_data_${{ matrix.fetch }}"
          delete-branch: "true"
          draft: "false"
          signoff: "false"
          body: |
            [data] update searx.data - ${{ matrix.fetch }}
          labels: |
            data

      - name: Display information
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
