---
name: Security

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "42 05 * * *"
  # TODO: Remove this
  pull_request:
    branches:
      - container-gha

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  container:
    name: Container
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: "false"

      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: "docker.io/searxng/searxng:latest"
          vuln-type: "os,library"
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
          ignore-unfixed: "false"
          format: "sarif"
          output: "./trivy-results.sarif"

      - name: Upload SARIFs
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "./trivy-results.sarif"
