---
name: Security

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "42 05 * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  container:
    if: github.repository_owner == 'searxng'
    name: Container
    runs-on: ubuntu-24.04-arm
    permissions:
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0
        with:
          persist-credentials: "false"

      - name: Sync GHCS from Docker Scout
        uses: docker/scout-action@f8c776824083494ab0d56b8105ba2ca85c86e4de  # v1.18.2
        with:
          organization: "searxng"
          dockerhub-user: "${{ secrets.DOCKER_USER }}"
          dockerhub-password: "${{ secrets.DOCKER_TOKEN }}"
          image: "registry://ghcr.io/searxng/searxng:latest"
          command: "cves"
          sarif-file: "./scout.sarif"
          exit-code: "false"
          write-comment: "false"

      - name: Upload SARIFs
        uses: github/codeql-action/upload-sarif@fdbfb4d2750291e159f0156def62b853c2798ca2  # v4.31.5
        with:
          sarif_file: "./scout.sarif"
